spring:
  application:
    name:service-quasar
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

server:
  port: 8081
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    path: /swagger-ui.html
